version: "3"

services:
  authelia:
    image: authelia/authelia:4.38.7
    container_name: authelia
    volumes:
      - ./config:/config
    networks:
      - shared
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=shared"
      - "traefik.http.routers.authelia.rule=Host(`auth.{{ containers_traefik_main_domain }}`,`auth.{{ containers_traefik_tunnel_domain }}`)"
      - "traefik.http.routers.authelia.entrypoints=websecure"
      - "traefik.http.routers.authelia.tls=true"
      - "traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://auth.{{ containers_traefik_tunnel_domain }}"
      - "traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email"
    expose:
      - 9091
    restart: always
    environment:
      - TZ=America/Toronto
    healthcheck:
      disable: true
networks:
  shared:
    external: true
